<p style="text-align: justify;"><b><br />Welcome to the bike2biker website.</b>&nbsp;Whether you are an advertiser or another user of the Website, access to or use of this website bike2biker (which includes our blog and all pages consisting of or containing that address, e.g. allads.bike2biker.com blog.bike2biker, and any page that is enabled for use by a mobile device) (the &ldquo;<b>Website</b>&rdquo; or &ldquo;<b>bike2biker</b>&rdquo;) and the provision of our advertising services on this Website are subject to you accepting our Agreement. That Agreement consists of these Copyright Notice, Legal Disclaimer and General Terms, the Advertising Terms and Conditions, our Privacy Policy our Policies Link and the Safety Guide Link appearing on the Website (the &ldquo;<b>Agreement</b>&rdquo;), all of which you should read carefully before you start to use the Website.</p>
<p style="text-align: justify;">By accessing and using this Website, you confirm that you have read, understand and accept that Agreement and that you agree to abide by its terms and conditions each time you access and use this Website. If you do not agree to all of this Agreement you should not use this Website.</p>
<p style="text-align: justify;">You agree that we may change this Agreement at any time and any change will become effective immediately once posted by us on the Website.&nbsp;Please check this Agreement from time to time as your continued use of the Website means you accept the Agreement on the Website at the time of your use.</p>
<p style="text-align: justify;"><b>1 Information About Us</b></p>
<p style="text-align: justify;">The Website bike2biker and Services is a website operated by rpwworld (&ldquo;we&rdquo;, &ldquo;us&rdquo; or &rdquo;our&rdquo;). Rory Walsh trading as rpwworld is registered at Clonmeen, Rhode, Co. Offaly.&nbsp;Our VAT number is IE6647473H.&nbsp;<br /><br /></p>
<p style="text-align: justify;"><b>2 Access to and Use of this Website and the bike2biker Service</b></p>
<p style="text-align: justify;">The services which are made available on this Website by us from time to time will, among other things, allow you to create, publish and manage written advertisements for goods for sale or for wanted goods; advertisements of the provision of services, contact other users of the Website; post comments on the bike2biker blog; search our database for advertisements regarding a specific product, seller and/or in a specific location; forward advertisements to people you know; invite people you know to view the Website; download or copy the portions of the information, data, text, sound, photographs, graphics, video, messages and other materials; and view third party material.</p>
<p style="text-align: justify;">Subject to this Agreement, you may use the Website for your own personal and commercial or non-commercial use to create, publish and manage written advertisements for goods for sale or for wanted goods or services; contact other users of the Website; post comments on the bike2biker blog; search our database for advertisements regarding a specific product, service, seller and/or in a specific location; forward advertisements to people you know; invite people you know to view the Website; view third party advertisements; download or copy the portions of the information, data, text, sound, photographs, graphics, video, messages and other materials available via the bike2biker Service.</p>
<p style="text-align: justify;">This Agreement applies to each visitor to, advertiser on and other user of our Website and the bike2biker Service.</p>
<p style="text-align: justify;">&nbsp;</p>
<p style="text-align: justify;">Once you have completed the process of submitting your advertisement we will send you an email confirming receipt of your order for bike2biker Services, this email does not constitute an acceptance of your order. Your order for posting an advertisement on our Website will not be accepted and an agreement concluded between us and you until the payment for bike2biker Services has been received by us. &nbsp;By submitting your advertisement to us, you are deemed to have agreed to this Agreement.</p>
<p style="text-align: justify;">Once your advertisement is posted on the Website your request for our services cannot be cancelled at that stage. Prior to the advertisement appear on the Website you may cancel the advertisement by contacting us at <a href="mailto:info@bike2biker.com">info@bike2biker.com<br /><br /></a></p>
<p style="text-align: justify;"><b>3 Using and Accessing the Website, Content and the bike2biker Service</b></p>
<p style="text-align: justify;">When creating an advertisement on the Website you agree to provide accurate, current and complete information and to promptly update the information you provide to us when it changes. Please refer to our Advertising Terms &amp; Conditions prior to posting any advertisement.</p>
<p style="text-align: justify;">We have the right to disable, suspend or restrict any password, username, mobile number, IP address or other method that we may allow to be used on the Website from time to time to identify users (whether chosen by you or allocated by us) (a &ldquo;User Identifier&rdquo;), at any time, at our discretion, including if, in our opinion, you have failed to comply with any of the provisions of this Agreement.</p>
<p style="text-align: justify;">You may not: (i) enter, select, submit or use a false name or an email address owned or controlled by another person with the intent to impersonate that person, (ii) use a User Identifier without appropriate authorisations or rights or (iii) use or submit a mobile number or email to us in respect of which you are not the registered owner, bill-payer and or account holder. We reserve the right in our sole discretion to refuse registration of, suspend or cancel a User Identifier&rsquo;s use or access rights to the Website without notice. You shall be responsible for maintaining the confidentiality of your User Identifier(s) and are fully responsible for all activities that occur under your User Identifier in connection with this Agreement. Any User Identifiers created by you or submitted for your access to the bike2biker Service and Website shall be for your personal use only and are non-transferable.</p>
<p style="text-align: justify;">You agree to (a) immediately notify us of any unauthorised use of your User Identifier as registered on our Website or submitted to us by you, or any other related breach of security and (b) if we from time to time allow you to login to restricted areas of the Website using an User Identifier, ensure that you logout at the end of each session following the instructions on the Website. We cannot and will not be liable for any loss or damage arising from your failure to comply with this section.</p>
<p style="text-align: justify;">If you forget or lose your User Identifier details used for the purposes of accessing restricted areas of the Website, you should request these from us by visiting the &ldquo;Forgotten&rdquo; section of the Website.</p>
<p style="text-align: justify;">As a condition of your access and use of our Website and/or the bike2biker Service, you warrant to us that you have the right, authority and capacity to enter into and be bound by this Agreement.</p>
<p style="text-align: justify;">We have no obligation to monitor or moderate any user&rsquo;s activity or use of our Website and/or the bike2biker Service, however we retain the right at all times to monitor, retain and disclose any information as necessary to satisfy any applicable law, regulation, legal process or regulatory authority request or to determine compliance with this Agreement.</p>
<p style="text-align: justify;">Without any admission of liability, we may from time to time assess any possible risks for users from third parties when they use the Website and/or the bike2biker Service, and we will decide in each case whether it is appropriate to use moderation or pre-approval of advertisements on the Website (including what kind of moderation to use) in the light of those risks. We expressly exclude our liability for any loss or damage arising from the use of the Website and/or the bike2biker Service by a user in contravention of our Agreement, whether the service is moderated or not and whether or note an advertisement has been reviewed by us prior to appearing on the Website.</p>
<p style="text-align: justify;">We do encourage the use by you of the &ldquo;Report Ad&rdquo; mechanism which we have placed on the Website which allows you to report any Content that is in breach of this Agreement or in any other way objectionable.</p>
<p style="text-align: justify;">The use of the Website and/or the bike2biker Service by a minor (an individual under 18 years of age) is subject to the consent of their parent or guardian and our contract is with the parent or guardian, who is responsible for the minor&rsquo;s compliance. We advise parents or guardians who permit minors to use the Website and/or the bike2biker Service that it is important that they communicate with minors about their safety online, as moderation or vetting of advertisements is not guaranteed or fool proof. Minors who are using any interactive service should be made aware of the potential risks to them.</p>
<p style="text-align: justify;">You are responsible for making all arrangements necessary for you to have access to our Website and/or the bike2biker Service.&nbsp;You are also responsible for ensuring that all persons who access our Website and/or the bike2biker Service through your internet connection, including any minors, are aware of these terms, and that they comply with them.</p>
<p style="text-align: justify;">Access to our Website and/or the bike2biker Service is permitted on a temporary basis, and we reserve the right to at any time and without liability to withdraw, suspend or amend any aspect or feature of the Website and/or the bike2biker Service without notice or liability.<br /><br /></p>
<p style="text-align: justify;"><b>4 Restrictions On Right to Use</b></p>
<p style="text-align: justify;">You agree that you shall not (and you agree not to allow any third party to):</p>
<ol style="text-align: justify;" start="1">
<li>a.&nbsp;&nbsp;&nbsp;      modify, adapt, translate, or reverse engineer any portion of the Website      and/or the bike3biker Service;</li>
<li>b.&nbsp;&nbsp;&nbsp;      remove any copyright, trade mark or other proprietary rights notices      contained in or on the Website and/or the bike2biker Service or in or on      any Content or other material obtained via the Website and/or the bike2biker      Service;</li>
<li>c.&nbsp;&nbsp;&nbsp;      use any robot, spider, website search/retrieval application, or other      automated device, process or means to access, retrieve or index any      portion of the Website and/or the biker2biker Service;</li>
<li>d.&nbsp;&nbsp;&nbsp;      access, retrieve or index any portion of the Website and/or the bike2biker      Service for purposes of constructing or populating any database;</li>
<li>e.&nbsp;&nbsp;&nbsp;      collect any information about other users or users of the Website and/or      the bike2biker Service (including User Identifiers) for any purpose other      than to use the Website for the purposes of responding to advertisements      or to use the Website in the manner intended by us;</li>
<li>f.&nbsp;&nbsp;&nbsp;&nbsp;      reformat or frame any portion of the web pages that are part of the      Website and/or the bike2biker Service;</li>
<li>g.&nbsp;&nbsp;&nbsp;      create user accounts by automated means or under false or fraudulent      pretences or create multiple log ins;</li>
<li>h.&nbsp;&nbsp;&nbsp;      create or transmit unwanted electronic communications such as &ldquo;spam&rdquo; to      other users of the Website and/or the bike2biker Service or otherwise      interfere with other user&rsquo;s enjoyment of the Website and/or the bike2biker      Service;</li>
<li>i.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      transmit any viruses, worms, defects, Trojan horses or other items of a      destructive nature;</li>
<li>j.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      use the Website or the bike2biker Service to violate the security of any      computer network, crack passwords or security encryption codes, transfer      or store illegal material including that are deemed threatening or      obscene;</li>
<li>k.&nbsp;&nbsp;&nbsp;      copy or store any Content offered on the Website for other than your own      use;</li>
<li>l.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      use any device, software or routine that interferes with the proper      working of the Website and/or the bike2biker Service, or otherwise attempt      to interfere with the proper working of the Website and/or the bike2biker      Service;</li>
<li>m.&nbsp;&nbsp;      take any action that imposes, or may impose in our sole discretion, an      unreasonable or disproportionately large load on our IT infrastructure;</li>
<li>n.&nbsp;&nbsp;&nbsp;      use the Website and/or the bike2biker Service, intentionally or      unintentionally, to violate any applicable law;</li>
<li>o.&nbsp;&nbsp;&nbsp;      collect or store personal data about other users in connection with the      prohibited activities described in this paragraph;</li>
<li>p.&nbsp;&nbsp;&nbsp;      engage in or promote any of the following (or what we deem similar):      surveys, contests,&nbsp;<a href="http://www.nca.ie/index.jsp?a=259&amp;n=192&amp;p=135">pyramid schemes</a>, chain letters, get rich      quick promotions, profit sharing promotions, unsolicited e-mailing or      spamming via the Website;</li>
<li>q.&nbsp;&nbsp;&nbsp;      impersonate any person or entity; or</li>
<li>r.&nbsp;&nbsp;&nbsp;&nbsp;      upload, post, e-mail, transmit or otherwise make available using the      Website any material that you do not have a right to make available under      any law or contractual obligation which includes a breach of third party      intellectual property rights.</li>
</ol>
<p style="text-align: justify;"><i>As per our&nbsp;</i><a title="Please see our full advertising terms and conditions." target="_blank" href="http://help.donedeal.ie/info/advertising-terms-conditions-23-jun-2010"><i>Advertising terms and conditions</i></a><i>: &ndash; bike2biker (&ldquo;we&rdquo;, &ldquo;us&rdquo; or &rdquo;our&rdquo;) reserves the absolute right at our sole discretion, without being obliged to give any reason, to reject, amend or remove any Content posted or submitted by you any time without notice to you. We reserve the right to monitor and to review all Content submitted to us, accessed on or published on bike2biker at any time.<br /><br /></i></p>
<p style="text-align: justify;"><b>5 Content Standards</b></p>
<p style="text-align: justify;">These provisions apply to any and all Content which you contribute to our Website and/or the bike2bikerl Service, and to any interactive services associated with it.</p>
<p style="text-align: justify;">You must comply with the spirit of the following standards as well as the letter. The standards apply to each part of any Content as well as to its whole.</p>
<p style="text-align: justify;">You are solely responsible for any Content that you submit, publish or display on the Website or transmit to other Website users.</p>
<p style="text-align: justify;">You are solely responsible for your advertisements listed on our Website. You understand that all information publicly posted or privately transmitted through the Website is the sole responsibility of the person from which such content originated and that we will not be liable for any errors or omissions in any content or as a result of any user&rsquo;s use of the Website. You understand that we cannot guarantee the identity of any other users with whom you may interact in the course of using the bike2biker Service. Additionally, we cannot guarantee the authenticity of any data which users may provide about themselves or relationships they may describe.</p>
<p style="text-align: justify;">By posting Content on the Website, you grant to us, and you represent and warrant that you have the right to grant, us, our contractors, and the users of the Website an irrevocable, perpetual, royalty-free, fully sub-licensable, fully paid up, worldwide license to use, copy, publicly perform, digitally perform, publicly display, and distribute such Content and to prepare derivative works of, or incorporate into other works, such Content. This licence is non-exclusive, except you agree that we shall have the exclusive right to exercise this license to the extent of combining your Content with the Content of other users for purposes of constructing or populating a searchable database of advertisements. You understand that this licence allows us to reformat, excerpt, or translate any materials submitted by you.</p>
<p style="text-align: justify;">The following is a partial list of the criteria that Content must comply with. Content must:</p>
<ol style="text-align: justify;" start="1">
<li>a.&nbsp;&nbsp;&nbsp;      &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;be accurate (where it      states facts).</li>
<li>b.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; be genuinely held (where it states      opinions).</li>
<li>c.&nbsp;&nbsp;      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;comply with applicable      law in Ireland, Northern Ireland and in any country from which they are      posted.</li>
<li>The      following is a partial list of the type of Content that is prohibited on      the Website. Content must not:</li>
<li>a.&nbsp;&nbsp;&nbsp;      comment on, defame, abuse, harass, stalk, threaten or otherwise offend      others;</li>
<li>b.&nbsp;&nbsp;&nbsp;      be unlawful, obscene, defamatory, seditious, indecent, offensive, liable      to incite racial hatred, discriminatory, menacing, scandalous,      inflammatory, be in breach of confidence, be in breach of privacy or be      inappropriate;</li>
<li>c.&nbsp;&nbsp;&nbsp;      breach any applicable laws or regulations;</li>
<li>d.&nbsp;&nbsp;&nbsp;      deceive or mislead any person and/or entity:</li>
<li>e.&nbsp;&nbsp;&nbsp;      falsely state, impersonate, or otherwise misrepresent your identity,      including but not limited to the use of a pseudonym, or misrepresenting      your current or previous positions and qualifications, or your affiliations      with a person or entity, past or present:</li>
<li>f.&nbsp;&nbsp;&nbsp;&nbsp;      upload, post, email, transmit or otherwise make available any content or      initiate communications which include information that you do not have the      right to disclose or make available under any law or under contractual or      fiduciary relationships (such as insider information, or proprietary and      confidential information learned or disclosed as part of employment      relationships or under nondisclosure agreements):</li>
<li>g.&nbsp;&nbsp;&nbsp;      upload, post, email, transmit or otherwise make available any content or      initiate communication that infringes upon patents, trademarks, trade      secrets, copyrights or other proprietary rights:</li>
<li>h.&nbsp;&nbsp;&nbsp;      upload, post, email, transmit or otherwise make available any unsolicited      or unauthorised advertising, promotional materials, &ldquo;junk mail,&rdquo; &ldquo;spam,&rdquo;      &ldquo;chain letters,&rdquo; &ldquo;<a href="http://www.nca.ie/index.jsp?a=259&amp;n=192&amp;p=135">pyramid schemes</a>,&rdquo; or any other form of      solicitation;</li>
<li>i.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      upload, post, email, transmit or otherwise make available any material      that contains software viruses or any other computer code, files or      programs designed to interrupt, destroy or limit the functionality of any      computer software or hardware or telecommunications equipment; and/or</li>
<li>j.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      interfere with or disrupt the Website or servers or networks connected to      the Website, or disobey any requirements, procedures, policies or      regulations of networks connected to the Website.</li>
</ol>
<p style="text-align: justify;">We do not control the Content posted by users via the bike2biker Service, including the content of any advertisements or blog postings, and we do not guarantee the accuracy, integrity or quality of such Content. You understand that by using the Website and/or the bike2biker Service, you may be exposed to Content that is offensive, indecent or objectionable. You are responsible for complying with all laws applicable to the Content you submit to the Website via the bike2biker Service. We may refuse any bike2biker Service without prior notice to any user for any or no reason.</p>
For further information, please see our&nbsp;<a href="http://help.donedeal.ie/info/advertising-terms-conditions">Advertising Terms and Conditions</a>.<br /><br />
<p style="text-align: justify;"><b>6 Suspension and Termination</b></p>
<p style="text-align: justify;">You agree that we may, with or without cause, immediately delete your advertisement [and terminate your access to the bike2biker Service or User Identifier] without prior notice at our sole discretion. The deletion or otherwise of an advertisement should not be viewed as an indication of wrongdoing on the part of the advertiser.</p>
<p style="text-align: justify;">Without limiting the foregoing, the following may lead to a deletion by us of a user&rsquo;s advertisement and/or termination of access to the bike2biker Service (a) a breach of this Agreement, (b) a request by law enforcement, Gardai / PSNI, police or other government agencies about you or any Content that you have submitted to us, (c) a request by you (self-initiated deletions), (d) unexpected technical issues or problems and (e) extended periods of inactivity. Deletion of a user advertisement and termination of access to the bike2biker Service may result in the removal of all Content that we may decide to delete. It may also result in preventing your further use of the Website or a User Identifier, depending on the circumstances. Furthermore, you agree that all termination of this Agreement or your use of the Website by us shall be made in our sole discretion and that we shall not be liable to you nor any third party for any termination of your account or access to the Website or removal of Content.</p>
<p style="text-align: justify;">You understand and agree that we may review and delete any advertisements, blog postings or other Content that in our sole judgment breach this Agreement or which might be offensive, illegal or that might violate the rights of, harm, or threaten the safety of other users of our Website or us.</p>
<p style="text-align: justify;">We reserve the right to investigate and we will determine, in our discretion, whether there has been a breach of this Agreement through your use of our Website and/or the bike2biker Service. When a breach of this agreement has occurred, we may take such action as we deem appropriate.</p>
<p style="text-align: justify;">Failure by you to comply with this Agreement may result in our taking all or any of the following actions:</p>
<ol style="text-align: justify;" start="1">
<li>immediate,      temporary or permanent withdrawal of your right to use our Website and/or      the bike2biker Service;</li>
<li>immediate,      temporary or permanent removal of any posting, material or Content      uploaded by you to our Website;</li>
<li>issue      of a public (via the Website) or private warning to you;</li>
<li>limit      the amount of postings you may make;</li>
<li>suspension,      restriction or limitation of any rights or permissions associated with a      User Identifier;</li>
<li>legal      proceedings against you for reimbursement of all costs on an indemnity      basis (including, but not limited to, reasonable administrative and legal      costs) resulting from the breach;</li>
<li>other      legal action against you; and/or</li>
<li>disclosure      of such information to law enforcement authorities as we reasonably feel      is necessary.</li>
</ol>
<p style="text-align: justify;">We exclude liability for actions taken in response to breaches of the content standards and restrictions of use. The responses described in this Agreement are not limited, and we may take any other action we reasonably deem appropriate.<br /><br /></p>
<p style="text-align: justify;"><b>7 Your Concerns and Complaints </b></p>
<p style="text-align: justify;">If you have any concerns about material which appears on our Website or if you believe that Content posted on the Website breaches this Agreement or is in any other way objectionable, please notify us through the &ldquo;<a href="http://help.donedeal.ie/info/how-report-ad">Report Ad</a>&rdquo; mechanism on the Website or send a letter to bike2biker, Clonmeen, Rhode, Co. Offaly, Ireland specifying the full details of your concern or complaint, specifying the reasons for your concern or complaint making clear reference to any connected such Content.</p>
<p style="text-align: justify;">If you do not provide us with sufficient information, we maybe unable to process your complaint. We reserve the right to investigate and we will determine, in our discretion, what action (if any) to take. You are solely responsible for your interactions with other users of the Website. While we reserve the right to monitor or to intervene in disputes between you and other users, we have no obligation to do so.</p>
<p style="text-align: justify;">We will make all reasonable endeavours to respond to complaints received as soon as possible, and our aim is to respond to all complaints within one working day.&nbsp;However, please note that from time to time it may take longer than one working day to deal with complaints.</p>
<p style="text-align: justify;"><b>8 Disputes with Third Parties</b></p>
<p style="text-align: justify;">You must tell us immediately if anyone makes or threatens to make any claim or issue legal proceedings against you relating to your use of the Website and/or the bike2biker Service. You will, at our request, immediately stop the act complained of. If we ask you to, you must confirm the details of the claim in writing. If you fail to stop the act or acts complained of we reserve the tight to take any and all appropriate action against you under the terms of the Agreement.<br /><br /></p>
<p style="text-align: justify;"><b>9 Payment for Advertisements</b></p>
<p style="text-align: justify;">Publication of an advertisement is subject to payment of a fee to bike2biker (the &ldquo;Fee&rdquo;). The Fee is set out on our Website and displayed to you in the course of you offering to place an ad with us.&nbsp;The Fee for all bike2biker Services is quoted and is payable in Euro or GDP deepening on the country or residency. All prices are stated inclusive of valued added tax (VAT) at the relevant rate.</p>
<p style="text-align: justify;">This Fee may be paid using Paypal, through your telephone bill or with credit or debit card. &nbsp;If you choose to pay using Paypal, you will be brought to the Paypal website,&nbsp;<a href="https://www.paypal.com/ie">https://www.paypal.com/ie</a>, and you will be subject to Paypal&rsquo;s User Agreement (<a href="https://cms.paypal.com/ie/cgi-bin/?&amp;cmd=_render-content&amp;content_ID=ua/UserAgreement_full&amp;locale.x=en_US">https://cms.paypal.com/ie/cgi-bin/?&amp;cmd=_render-content&amp;content_ID=ua/UserAgreement_full&amp;locale.x=en_US</a>) and Privacy Policy (<a href="https://cms.paypal.com/ie/cgi-bin/?&amp;cmd=_render-content&amp;content_ID=ua/Privacy_full&amp;locale.x=en_US">https://cms.paypal.com/ie/cgi-bin/?&amp;cmd=_render-content&amp;content_ID=ua/Privacy_full&amp;locale.x=en_US</a>). We are not responsible for Paypal&rsquo;s services and you should separately review and confirm that you are agreeable to Paypal&rsquo;s terms prior to instructing them to pay us.<br /><br /></p>
<p style="text-align: justify;"><b>10 About Published Ads and Duration of the Ads</b></p>
<p style="text-align: justify;">Ads will be displayed for a period until the item is sold and is the responsibility of the user to remove. bike2bike reserve the right to remove ads if they are deemed inactive.</p>
<p style="text-align: justify;">Content which comprises advertising material will appear on the Website. Individual advertisers are solely responsible for the content of the material which they submit to us including ensuring that it complies with relevant legislation. We accept no responsibility for the content of any business and/or advertising material, including, without limitation, any error, omission or inaccuracy.</p>
<p style="text-align: justify;">Please note that the content of the published ads is provided by external users, and do not represent any views or opinions of bike2biker, nor should they purport to do so.</p>
<p style="text-align: justify;">Accordingly, we require that every care is taken by you or on your behalf in drafting the content of your advertisements in order to ensure that they are not in any way defamatory, illegal or in any other way harmful to a third party as you are solely responsible as author and publisher of your advertisement.</p>
<p style="text-align: justify;">Advertisements published on bike2biker are also subject to our&nbsp;<a href="http://help.donedeal.ie/info/advertising-terms-conditions">Advertising Terms &amp; Conditions</a>.<br /><br /></p>
<p style="text-align: justify;"><b>11 Intellectual Property</b></p>
<p style="text-align: justify;">We are the owner or the licensee of all intellectual property rights in our Website and the bike2biker Service, and in the Content published on it.&nbsp;Those works are protected by copyright laws, trade mark laws, database laws and treaties around the world.&nbsp;All such rights are reserved.</p>
<p style="text-align: justify;">The Website and the bike2biker Service (including, but not limited to, text, photographs, graphics, video and audio Content) are protected by copyright as works, databases, collective works and/or compilations under the copyright laws of Ireland, Northern Ireland and other countries. All individual ads, articles, Content and other elements comprising the Website and the bike2biker Service are also copyrighted works. Except for the Content submitted by users, the Website, User Identifiers and the bike2biker Service and all aspects of them, including all copyrights, trade marks, and other intellectual property or proprietary rights, are owned by us or our licensors. You acknowledge that the Website, User Identifiers and the bike2biker Service and any underlying technology or software used in connection with the Website and the bike2biker Service contains our proprietary information. You may not modify, reproduce, distribute, create derivative works of, publicly display or in any way exploit, any of the content, software, and/or materials available on the Website, or the bike2biker Service in whole or in part except as expressly provided. Except as expressly and unambiguously provided in this Agreement, we and our advertisers, licensors or suppliers do not grant you any express or implied rights, and all rights in the bike2biker Service not expressly granted by us to you are retained by us or our licensors.</p>
<p style="text-align: justify;">If it is determined that you retain moral rights in the Content, you confirm and agree that (a) you do not require that any personally identifying information be used in connection with the Content, or any derivative works of or upgrades or updates to the Content; (b) you have no objection to the publication, use, modification, deletion and exploitation of the Content by us or our licensees, successors and assigns; (c) you forever waive and agree not to claim or assert any entitlement to any and all moral rights of an author in any of the Content; and (d) you forever release us, and our licensees, successors and assigns, from any claims that you could otherwise assert against us by virtue of any such moral rights.</p>
<p style="text-align: justify;">You may reproduce material from our Website for your own personal, non-commercial reference and you may draw the attention of others to material posted on our Website.&nbsp;Reproduction of material from our Website for other purposes is permitted, provided that the source of the material is acknowledged.&nbsp;In particular, you must not cache any of the contents for access by third parties, nor mirror, scrape or frame any of the content of the Website, nor incorporate it into another website without our express written permission. You may also permit your computer to make an electronically stored, transient copy of the content on our Website for the purposes of viewing it while connected to the internet only.</p>
<p style="text-align: justify;">You must not modify the paper or digital copies of any materials you have printed off or downloaded in any way, and you must not use any illustrations, photographs, or any graphics separately from any accompanying text.</p>
<p style="text-align: justify;">Our status (and that of any partners, advertisers or third parties identified on our Website) as the authors of material on our Website must always be acknowledged by you.</p>
<p style="text-align: justify;">You must not use any part of the Content on our Website for commercial purposes without obtaining a licence to do so from us.</p>
<p style="text-align: justify;">If you print off, copy or download any part of our Website in breach of this Agreement, your right to use our Website will cease immediately and you must, at our option, return or destroy any copies of the materials that you have made.</p>
<p style="text-align: justify;"><b>13 Disclaimer of Liability</b></p>
<p style="text-align: justify;">Bike2biker provides this Website and/or the bike2biker Service on an &ldquo;as is&rdquo; basis only. You should not rely on any Content and/or other material on our Website and/or the bike2biker Service to make (or refrain from making) any decision or to take (or refrain from taking) any action on which reliance should be placed.&nbsp;We disclaim all liability and responsibility arising from any reliance placed on such Content and/or materials by any user of our Website and/or the bike2bikerl Service, or by anyone who may be informed of any of the Content.&nbsp;We accept no responsibility for keeping the information in the Website and/or the bike2bikerl Service up to date or complete or liability for any failure to do so.</p>
<p style="text-align: justify;">The Content and other material displayed on our Website is provided without any guarantees, conditions or warranties as to its accuracy.&nbsp;To the extent permitted by law, we expressly exclude:</p>
<ol style="text-align: justify;" start="1">
<li>all      conditions, warranties and other terms which might otherwise be implied by      statute, common law or the law of equity; and</li>
<li>any      liability for any direct, indirect or consequential loss or damage      incurred by any user in connection with our Website and/or bike2biker      Service or in connection with the use, inability to use, or results of the      use of our Website and/or bike2biker Service, any websites linked to it      and any materials posted on it, including, without limitation any      liability for loss of income or revenue, loss of business, loss of profits      or contracts, loss of anticipated savings, loss of data, loss of goodwill,      wasted management or office time and for any other loss or damage of any      kind, however arising and whether caused by tort (including negligence),      breach of contract or otherwise, even if foreseeable.</li>
</ol>
<p style="text-align: justify;">Nothing in this Agreement shall exclude or limit our liability in relation to any damages arising from death or personal injury caused by the negligence of bike2biker or for fraudulent misrepresentation or misrepresentation as to a fundamental matter, or any other liability which cannot be excluded or limited under applicable law.</p>
<p style="text-align: justify;">We shall not be liable for any failure to perform any of our obligations under this Agreement caused by matters beyond our reasonable control. Under no circumstances will we be liable in any way for any Content, including, but not limited to, any errors or omissions in any Content, or any loss or damage of any kind incurred as a result of the use of, access to, or denial of access to any Content on the Website.</p>
<p style="text-align: justify;">Although we make all reasonable endeavours to ensure that the Website is free from viruses and defects, we will not be liable for any loss or damage caused by a distributed denial-of-service attack, viruses, malicious or impairing computer programs or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of our Website and/or bike2biker Service or to your downloading of any material posted on it, or on any website linked to it.</p>
<p style="text-align: justify;">We do not guarantee the security of the online services or any systems connected with the use of the Website (including the internet and your hardware and software) used in accessing the services, or any information passed through such systems. We do not guarantee access to the Website or any systems used in accessing our services will be continuous or virus or error free.</p>
<p style="text-align: justify;">Any material downloaded or otherwise obtained through the use of the Website is done at your own discretion and risk and that you will be solely responsible for any damage to your computer system or loss of data that results from the download of any such material. No advice or information, whether oral or written, obtained by you from us or through or from the Website shall create any warranty not expressly stated in this Agreement.</p>
<p style="text-align: justify;"><b>14 Indemnity </b></p>
<p style="text-align: justify;">You agree to indemnify and hold biketbiker, our parent, subsidiaries, officers, directors, shareholders, employees, agents, licensors and suppliers harmless from and against any claims, actions or demands, liabilities and settlements, including without limitation, reasonable legal and accounting fees resulting from, or alleged to result from, your access to or use of this Website, the Content or the bike2biker Service in a manner that breaches or is alleged to breach this Agreement, or the infringement by you, or any third party using your user identification name or password, of any intellectual property or other right of any person or entity.</p>
<p style="text-align: justify;"><b>15 Disclaimer of Endorsement</b></p>
<p style="text-align: justify;">Content on the Website referring to any products, process or service by trade name, trade mark, manufacturer or otherwise, does not constitute or imply its endorsement, recommendation or validation by us. We have not independently verified the accuracy of any description of any goods or services advertised on the Website. The views, opinions and other Content posted by users on this Website are not ours, shall not be attributed to us by you and shall not be used by you for any advertising or product endorsement purposes unless we expressly authorise it.</p>
<p style="text-align: justify;">&nbsp;</p>
<p style="text-align: justify;"><b>16 Uploading Content to Our Website </b></p>
<p style="text-align: justify;">Whenever you make use of a feature that allows you to upload Content to our Website, or to make contact with other users of our Website, you must comply with this Agreement, including</p>
<p style="text-align: justify;">our&nbsp;<a href="http://help.donedeal.ie/info/privacy-policy">Privacy Policy</a>. You warrant that any such Content does comply with this Agreement, and you indemnify us for any breach of that warranty.</p>
<p style="text-align: justify;">Any Content you upload to our Website will be considered non-confidential and non-proprietary, and we have the right to use, copy, distribute and disclose to third parties any such material for any purpose. We also have the right, at our discretion, to disclose your identity to any third party who is claiming that any Content posted or uploaded by you to our Website constitutes a violation of their intellectual property rights, or of their right to privacy.</p>
<p style="text-align: justify;"><b>17 Linking to Our Website</b></p>
<p style="text-align: justify;">You may link to our Website, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, sponsorship or endorsement on our part without our express written permission or in order to directly compete with the Website and redirect traffic from it. You must not establish a link from any website that is not owned by you.</p>
<p style="text-align: justify;">We reserve the right to withdraw linking permission without notice.&nbsp;Our Website (in whole or in part) must not be framed on any other website or in any other way altered or displayed in a different manner to the manner which we display it.</p>
If you wish to make any use of material on our Website other than in the manner that is in this Agreement, including as set out above please&nbsp;<a href="http://help.donedeal.ie/contact">contact us</a>.
<p style="text-align: justify;"><b>18 Links from Our Website</b></p>
<p style="text-align: justify;">Where our Website contains links to other websites and resources provided by Banner Advertisers, advertisers using our Website or other third parties, these links are provided for your information only.&nbsp;We have no control over the contents of those websites or resources, and we accept no responsibility for them or for any loss or damage that may arise from your use of them.&nbsp;If you link to any such websites you leave our Website and do so entirely at your own risk.</p>
<p style="text-align: justify;"><b>19 Contact From Us</b></p>
<p style="text-align: justify;">In the course of providing you services and in respect of your use of the Website, we may need to communicate with you via email or the other details that you have submitted to us. You agree to receive emails which are specific to your order and necessary for the normal functioning of the Website, including emails which help inform users about functionality of the Website.</p>
<p style="text-align: justify;"><b>20 Our Website Privacy Policy</b></p>
<p style="text-align: justify;">We at bike2iker respect your right to privacy and comply with our obligations under the Data Protection Acts 1988 and 2003, as amended. The purpose of our Website&nbsp;<a href="http://help.donedeal.ie/info/privacy-policy">Privacy Policy</a>&nbsp;</p>
<p style="text-align: justify;">&nbsp;is to outline how we deal with any personal data you provide to us while visiting this Website, and it forms part of our Agreement with. Naturally, if you are not happy with our Website Privacy Policy you should not use this Website.</p>
<p style="text-align: justify;">Any external links to other websites are clearly identifiable as such, and we are not responsible for the content or the privacy policies of these other websites.</p>
<p style="text-align: justify;"><b>21 Governing Law and Jurisdiction</b></p>
<p style="text-align: justify;">This Agreement shall be governed by, and construed in accordance with Irish law and any dispute which may arise out of or in connection with this Agreement or the legal relationship established by them, shall be subject to the exclusive jurisdiction of the Irish Courts, although we retain the right to bring proceeding against you for breach of this Agreement in your country of residence or any other relevant country.&nbsp;The rights and remedies contained in this Agreement are cumulative and not exclusive of rights or remedies provided by law.</p>
<p style="text-align: justify;"><b>22 Waiver</b></p>
<p style="text-align: justify;">A failure to exercise or delay in exercising a right or remedy provided by this Agreement or by law does not constitute a waiver of the right or remedy or a waiver of other rights or remedies.&nbsp;No single or partial exercise of a right or remedy provided by this Agreement or by law prevents further exercise of that right or remedy or the exercise of another right or remedy.</p>
<p style="text-align: justify;"><b>23 Severability</b></p>
<p style="text-align: justify;">In the event that any clause or any part of any clause in this Agreement is declared invalid or unenforceable, by the judgment or decree by consent or otherwise of a court of competent jurisdiction from whose decision no appeal is or can be taken, all other provisions contained in this Agreement shall remain in full force and effect and shall not be affected by such finding for the term of this Agreement.<br /><br /></p>
<p style="text-align: justify;"><b>24 Assignment and Entire Agreement</b></p>
<p style="text-align: justify;">We may assign or subcontract any or all of our rights and obligations of our Agreement with you to a third party at any time, at our discretion.&nbsp;You may not, without our prior written consent, assign or dispose of any of your rights or obligations arising under this Agreement.</p>
<p style="text-align: justify;">This Agreement contains the entire agreement and understanding between the parties relating to our Website, and supersedes any and all prior agreements, arrangements, statements and understandings, except for any fraud or fraudulent representation by either you or us. In the event of any inconsistency between the Privacy Policy and this Copyright Notice and Legal Disclaimer then this Copyright Notice and Legal Disclaimer takes priority.</p>
<p style="text-align: justify;"><b>25 Submissions</b></p>
<p style="text-align: justify;">You acknowledge and agree that any questions, comments, suggestions, ideas, feedback and other information about the Website and/or the bike2biker Service provided by you to us are non-confidential and may be used by us at our discretion.</p>
<p style="text-align: justify;">Thank you for visiting our Website.</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p><br /><br /></p>
<p><i><br /><br />&nbsp;</i></p>
<p><a href="mailto:info@bike2biker.com"><br /><br /><br /></a></p>
<br />