<p style="text-align: justify;"><b><br />bike2biker Privacy Policy<br />&nbsp;</b></p>
<p style="text-align: justify;"><b>Here at bike2biker we care about your privacy and we respect your privacy rights.<br />&nbsp;</b></p>
<p style="text-align: justify;">By using bike2biker, you permit the collection and use of your personal information as outlined below and you signify your agreement to this Privacy Policy. If you do not agree with these terms, you should not use bike2biker.com.</p>
<p style="text-align: justify;"><b>1. Introduction</b></p>
<p style="text-align: justify;">This website bike2biker, all pages containing that address and the services provided on this website, including any page that is enabled for use by a mobile device, (the &ldquo;bike2biker Website&rdquo;) are owned and operated by Rory Walsh, of Clonmeen, Rhode, Co. Offaly, Ireland (&ldquo;bike2biker&rdquo;, &ldquo;our&rdquo;, &ldquo;we&rdquo; or &ldquo;us&rdquo;). If you do not agree with these terms, you should not use the bike2biker Website.</p>
<p style="text-align: justify;">We at bike2biker respect your right to privacy and aim to comply with our obligations under the data protection legislation currently in force in Ireland. The purpose of this Website Privacy Policy is to outline how we deal with any personal data that we collect from you or that you provide to us while visiting the bike2biker Website. We use your information only as set out in this Privacy Policy. Naturally, if you are not happy with this Website Privacy Policy you should not use the bike2biker Website.</p>
<p style="text-align: justify;">This policy, together with our Terms and Conditions and any other documents referred to in them, sets out the basis on which any personal data we collect from you, or that you provide to us, will be processed by us. Please read the following carefully to understand our views and practices regarding your personal data and how we will treat it.</p>
<p style="text-align: justify;">By visiting the bike2biker Website, you are accepting the terms of this Website Privacy Policy and you permit the collection and use of your personal data as outlined in this Website Privacy Policy.</p>
<p style="text-align: justify;"><b>2. How we Collect Information relating to the bike2biker Website</b></p>
<p style="text-align: justify;">You can browse bike2biker.com without registering or telling us who you are or revealing any personal information about yourself.</p>
<p style="text-align: justify;">When registering as a user of bike2biker or during your time as a user of biker2biker you will be asked to provide information to us.&nbsp;We will inform you at the time of collecting other information from you whether you must provide the information to use bike2biker or a particular bike2biker Service or whether the provision of information requested by us is optional.&nbsp;We will inform you at the time of collecting information from you whether the information that you provide to us will be accessible to other users of bike2biker or by third parties so that you can decide whether to provide the information to us.</p>
<p style="text-align: justify;">We may collect and process the following data about you.</p>
<ol style="text-align: justify;">
<li>If you contact us, we may keep a record of that correspondence.</li>
<li>Information that you submit when you register for the bike2biker Website including your name, email address and telephone number.</li>
<li>Information that you submit when you use the bike2biker Website, for example in response to a blog post, in a message to us, when posting an advertisement, entering a competition or through any website communication channel.</li>
<li>The functionality that you use through the bike2biker Website including comments on our blog.</li>
<li>Details of transactions you carry out through bike2biker.</li>
<li>Call may be recorded by us from time to time.</li>
<li>Payment details (bike2biker.com retains no record of this information once payment has been completed).</li>
</ol>
<p style="text-align: justify;">Such information is only collected from you if you voluntarily submit it to us, and is only kept for as long as it is required for us to provide you with a high quality service, to comply with law or our contractual obligations or for reasonable record-keeping purposes.</p>
<p style="text-align: justify;">Other Data</p>
<p style="text-align: justify;">Like most websites, we gather statistical and other analytical information collected on an aggregate basis of all visitors to the bike2biker Website. This data comprises information that cannot be used to identify or contact you, such as demographic information regarding, for example, browser types, alphanumeric IDs, operating system, traffic data, location data,&nbsp;IP addresses, information regarding the volume and status of data transmission, click-through statistics, the name of the domain and host from which you access the Internet, the date and time you accesses portions of the bike2biker Website, and other anonymous statistical data involving the use of the bike2biker Website. This is statistical data about our users&rsquo; browsing actions and patterns, and we do not use them to identify any individual, except if required by the law or for the purposes of fraud protection, IT security and credit risk reduction.</p>
<p style="text-align: justify;"><b>3. Purposes for which we hold your Information</b></p>
<p style="text-align: justify;"><b>Personal Data</b></p>
<p style="text-align: justify;">Users of the bike2biker Service use the website to create advertisements for new and used motorbikes and bicycles for sale and wanted goods and to write comments on the bike2biker Blog. These advertisements and comments can then be accessed and read by other users of the website.&nbsp;If you choose to place an advertisement using the bike2bike Service, we will display a limited amount of personal information, such as your name and telephone number, so that interested parties may contact you.&nbsp;Additionally, we may use your email address to contact you on behalf of interested parties wishing to respond to your advertisements by email.&nbsp;&nbsp;&nbsp; We maintain a record of any conversations you have with other users of the bike2biker Website through the bike2biker safe mail service in connection with any advertisements. We monitor and retain such information for the security and safety of our users. We may use your advertisements, and the advertisements that you view to personalise the website and identify popular buy and sell sections.&nbsp;We may also display recently posted advertisements and recently sold goods to users of the bik2biker Website.</p>
<ol style="text-align: justify;">
<li>to provide you with the services you have ordered;</li>
<li>to carry out our obligations arising from any contracts entered into between you and us;</li>
<li>to deliver and maintain a high quality service and to improve and develop the services provided and the Website generally;</li>
<li>to allow you to access bike2biker and to participate in interactive features of our service, when you choose to do so;</li>
<li>to provide you with information, products or services that you request from us or that we feel may interest you, where you have consented to be contacted for such purposes;</li>
</ol> <ol style="text-align: justify;" start="6">
<li>to      contact you if required in connection with your order or to respond to any      communications you might send to us;</li>
<li>to      inform you about changes to our service, our agreement with you or website      that we believe will be of interest to you;</li>
<li>as bike2biker      Website is being actively developed we might contact you to get feedback      on the service provided;</li>
<li>for      the purposes of compiling statistics;</li>
<li>to      determine whether you are in compliance with our agreement with you and to      impose sanctions where necessary;</li>
<li>as      proof of identity before we disclose personal information to you that we      hold about you (in order to establish that we are disclosing the personal      information to you and not to someone pretending to be you);</li>
<li>to      process payments from or to you;</li>
<li>compare      information for accuracy, and verify it with third parties;</li>
<li>for      safety purposes (including maintaining a register of restricted users), to      provide you with customer support and to resolve technical or other      problems (where you have contacted us through our Customer Support&nbsp;</li>
<li>to      determine whether you or other users are in compliance with our agreement      relating to the bike2biker Website, including the policies appearing on the      bike2biker Website.</li>
</ol>
<p style="text-align: justify;">If you avail of our services offered on the bike2biker Website we may use your email address to send you updates or news regarding the bike2biker Service.&nbsp;If you do not wish to receive emails of this type, please contact us.</p>
<p style="text-align: justify;"><b>Other Data:</b></p>
<p style="text-align: justify;">We use the Other Data gathered from visitors to the bike2biker Website in an aggregate form to get a better understanding of where our visitors come from and to help us better design and organise the bike2biker Website.</p>
<p style="text-align: justify;"><b>Cookies</b></p>
<p style="text-align: justify;">This website uses &ldquo;cookies&rdquo;. A cookie is a little piece of data stored by the browser on the hard drive of your computer, at the request of our server. Cookies contain information that is transferred to your computer&rsquo;s hard drive.&nbsp;On revisiting bike2biker our computer server will recognise the cookie, giving us information about your last visit. We may use cookies (including flash cookies) to deliver content specific to your interests and to save your personal preferences so you do not have to re-enter them each time you connect to the bike2biker Website &ndash; our cookies are not available to other websites. Cookies help us to improve bike2biker and to deliver a better and more personalised service.&nbsp;They enable us:</p>
<ol style="text-align: justify;" start="1">
<li>to      estimate our audience size and usage pattern;</li>
<li>to      store information about your preferences, and so allow us to customise bike2biker      according to your individual interests; and</li>
<li>to      speed up your use of the bike2biker Service and searches.</li>
</ol>
<p style="text-align: justify;">You are always free to decline our cookies, if your browser permits, by activating the setting on your browser which allows you to refuse the setting of cookies. You are always free to ask your browser to indicate when a cookie is being sent. You can also delete cookie files from your computer at your discretion. Note that if you decline our cookies or ask for notification each time a cookie is being sent, this may affect your use of the bike2biker Website. For information on how to control your cookies go to <a href="http://www.allaboutcookies.org/">www.allaboutcookies.org</a>.</p>
<p style="text-align: justify;">We also participate in the Google Adsense programme and we allow Google and other third parties that participate in Google Adsense to use a type of cookie called the &ldquo;DoubleClick DART&rdquo; cookie also on our Website. Please note that Google is a third party and Clause 4 below applies to Google&rsquo;s use of cookies via our website. Google uses cookies to serve ads to you on the Website. A persistent cookie gets entered by your web browser into the cookie folder on your computer&rsquo;s hard drive. A persistentcookie remains in that cookie folder, which is maintained and governed by your web browser, after you close your browser program. The DoubleClick DART cookie is a persistent cookie used by Google in the ads served on the websites of its partners, such as websites displaying AdSense ads or participating in Google certified ad networks. The DoubleClick DART cookie consists of the name of the domain that set the cookie (&ldquo;ad.doubleclick.net&rdquo;), the lifetime of the cookie, and a &ldquo;value.&rdquo; DoubleClick&rsquo;s DART technology used by Google generates a unique series of characters for the &ldquo;value&rdquo; portion of the cookie.</p>
<p style="text-align: justify;">When you visit a Google partner&rsquo;s website and either view or click on an ad, a DoubleClick DART cookie may be dropped on your browser. The manner in which the &ldquo;DoubleClick DART&rdquo; cookie works enables Google and its partners to display ads to you on the Website and/or other sites on the Internet. You may opt out of the use of the DoubleClick DART used by Google. Instructions on how to opt-out are available from Google and are set out in this Google ad and content network privacy policy <a href="http://www.google.com/privacy_ads.html">http://www.google.com/privacy_ads.html</a> and more information regarding the &ldquo;DoubleClick DART cookie&rdquo; please visit:<a href="http://www.doubleclick.com/privacy/faq.aspx">http://www.doubleclick.com/privacy/faq.aspx<br /><br /></a></p>
<p style="text-align: justify;"><b>4. Disclosure of Information to Third Parties and Advertising</b></p>
<p style="text-align: justify;">We may provide Other Data to third parties, where such information is combined with similar information of other users of the bike2biker Website. For example, we might provide third parties with aggregate anonymised information regarding the number of unique users who visit the bike2biker Website, the demographic breakdown of our community users of the bike2biker Website, or the activities that visitors to the bike2biker Website engage in while on the bike2biker Website. The third parties to whom we may provide this information may include potential or actual advertisers, providers of advertising services (including website tracking services), commercial partners, sponsors, licensees, researchers and other similar parties.</p>
<p style="text-align: justify;">We use third-party advertising companies to serve ads when you visit the bike2biker Website. These companies may use information (not including your name, address, email address or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you on the bike2biker Website or on other third party websites that you visit. Further information about the use of cookies in delivering these advertisements is contained in Clause 3 above.</p>
<p style="text-align: justify;">We may also use such aggregate anonymised information to help advertisers reach the kind of audience they want to target (for example, women in the southeast of Ireland) when displaying advertisements on the bike2biker Website.&nbsp;We may make use of the personal data we have collected from you to enable us to comply with our advertisers&rsquo; wishes by displaying their advertisement to that target audience.&nbsp;You agree to these practices.</p>
<p style="text-align: justify;">We will not disclose your personal data to third parties unless you have consented to this disclosure or unless the third party is required to fulfil your order (in such circumstances, the third party is bound by similar data protection requirements). We will disclose your personal data if we believe in good faith that we are required to disclose it in order to comply with any applicable law, a summons, a search warrant, a court or regulatory order, or other statutory requirement. For the avoidance of doubt, we reserve the right to provide access to any data contained on our database to An Garda S&iacute;och&aacute;na where such data is required for the prevention, detection or investigation of offences or the apprehending or prosecution of offenders. We may provide such data, where we receive a written authorisation in advance from a member of An Garda S&iacute;och&aacute;na and on the strict understanding that the data is being provided solely for use by a member of An Garda S&iacute;och&aacute;na for the purposes identified to us in advance. &nbsp;We also reserve the right to provide remote access to our database to authorised members of An Garda S&iacute;och&aacute;na on an ongoing basis where such access, and the conditions of such access, have been agreed to by us in advance. Such access is provided in the interests of the safety and security of our users.</p>
<p style="text-align: justify;">Please note that if you post personal information on public sections of the bike2biker Website then you are consenting to giving a third party user of the bike2biker Website to use your data; we are not responsible for the manner in which those third parties may choose to allow them use your data.</p>
<p style="text-align: justify;">If you provide personal data to us, you understand and agree that we may disclose your personal data to the following third parties:</p>
<ol style="text-align: justify;" start="1">
<li>to      our hosting provider which acts as an agent of bike2biker.com;</li>
<li>to      our payment processing service providers;</li>
<li>if      you have indicated at any time while using the bike2biker Service that you      are happy to receive information or promotions from selected third parties      about goods and services which may be of interest to you, you consent to      us sending you such offers or information.&nbsp;If you wish to opt out of      receiving such offers, please contact us</li>
<li>any      member of our group of companies, which means our subsidiaries, our      ultimate holding company and its subsidiaries;</li>
<li>to a      prospective seller, shareholder or buyer of some or all of the shares in      the bike2biker Website and/or any of our businesses;</li>
<li>to a      third party if we are under a duty to disclose or share your personal data      with that third party in order to comply with any legal obligation, or in      order to enforce or apply our agreement with you or any other relevant      agreements, or to protect the rights, property or safety of the bike2biker      Website and/or our customers or others.&nbsp;This includes exchanging      information with third parties for the purposes of fraud protection, IT      security and credit risk reduction and statutory or other investigative      bodies, where such bodies have the statutory authority to request such      personal data or you have given your consent for us to disclose your      personal data in this manner.</li>
</ol>
<p style="text-align: justify;">We will notify you when information about you may be provided to third parties in ways other than explained in this Policy and you will have the option to prevent such information sharing at the time that we notify you.</p>
<p style="text-align: justify;">We reserve the right to transfer information (including your personal data) to a third party in the event of a sale, merger, liquidation, receivership, purchase or transfer of all or substantially all of the business or assets related to the bike2biker Website or all or part of bike2biker provided that the third party agrees to adhere to the terms of this Privacy Policy.</p>
<p style="text-align: justify;">You agree that you have access to other users&rsquo; personal information when you use the bike2biker Website, or as a result of any related communication or transaction. You agree that you will only use another user&rsquo;s personal information to contact the person for the purposes of buying or selling the goods or services to which the users&rsquo; personal information is connected. If other user subsequently agrees that you may use their personal information for any other purpose then that is a matter for you and the other person to agree. Unless you have the other bike2biker Website user&rsquo;s express permission or our express written permission you may not disclose or contact another user for any purpose other than to conduct transactions for goods or services advertised on the bike2biker Website.<br /><br /></p>
<p style="text-align: justify;"><b>5. Security, Transfer and Control of personal data</b></p>
<p style="text-align: justify;">We will take all reasonable steps (including appropriate technical and organisational measures) to protect your personal data that we hold in accordance with this Website Privacy Policy. However, the nature of the internet is such that we cannot guarantee or warrant the security of any information you transmit to us via the internet. No data transmission over the Internet can be guaranteed to be 100% secure and any transmission is at your own risk. You acknowledge that we are not responsible for any intercepted information sent via the internet and you hereby release us from any and all claims arising out of and related to the use of intercepted information in any unauthorised manner.</p>
<p style="text-align: justify;">If we have given you (or where you have chosen) a password which enables you to access certain parts of the bike2biker Website, you are responsible for keeping this password confidential.&nbsp;We ask you not to share a password with anyone.</p>
<p style="text-align: justify;">You should be aware that when you voluntarily disclose personally identifiable information and agree to make that information public on the bike2biker Website (e.g., name, telephone number) via advertisements, blog postings, tweets or in other areas of the bike2biker Website, then that information, along with any substantive information disclosed in your communication, can be collected, correlated and used by third parties. These third parties or other website users may use your information to send you unsolicited messages. Such activities are beyond our control. Please do not post any personal information on the bike2biker Website that you wish to keep private.</p>
<p style="text-align: justify;">It may be necessary to transfer your personal information to other group companies or service providers located in countries outside of the European Economic Area (EEA), including but not limited to the United States.&nbsp;This may happen where our servers or suppliers and service providers are based outside of the EEA or where you use our services and products while visiting countries outside of the EEA.&nbsp;The data protection and other laws of these countries may not be as comprehensive as those in Ireland or the EU but in these instances we will take steps to ensure that your privacy rights are respected.&nbsp;You agree that we may transfer your personal data on that basis.<br /><br /></p>
<p style="text-align: justify;"><b>6. Access to Information and Updating, Verifying and Deleting personal data</b></p>
<p style="text-align: justify;">At any time, you can make a written request to have access to all the personal data that we hold about you.&nbsp;You may inform us of any changes in your personal data and, in accordance with our obligations under the data protection legislation; we will update or delete your personal data accordingly. To make this request or to have your personal data updated, amended or removed from our database, please us this form. We will provide this information to you and may request a small administrative charge.</p>
<p style="text-align: justify;"><b>7. Changes to the bike2biker Website Privacy Policy</b></p>
<p style="text-align: justify;">Any changes we may make to our Privacy Policy in the future will be posted on this page and may be, where we consider it appropriate, notified to you by e-mail.&nbsp;You should visit this page periodically to review any changes to the Privacy Policy.<br /><br /></p>
<p style="text-align: justify;"><b>8. Links</b></p>
<p style="text-align: justify;">When you pay us you will leave the bike2biker Website and you will instruct one of our payment processing service providers (which include Paypal) to make a payment to us on your behalf.&nbsp;Please note that these providers have their own privacy policies and terms of use and that we do not accept any responsibility or liability for these policies, their terms or for the activities on those websites.</p>
<p style="text-align: justify;">Bike2biker may, from time to time, contain links to and from the websites of our partner networks, advertisers and affiliates as well as third party websites to which we have no affiliation. Users of the bike2biker Website may post links to other websites also.&nbsp;If you follow a link to any of these websites, please note that these websites have their own privacy policies and terms of use and that we do not accept any responsibility or liability for these policies or for the activities on those websites.</p>
<p style="text-align: justify;"><b>9. Access by children</b></p>
<p style="text-align: justify;">If you are aged 16 or under you must get one or your parents or a guardian&rsquo;s permission before providing personal data to us by using the bike2biker Website. If you do not have this permission you should not use the bike2biker Website. We may ask you at any time to confirm and produce this permission in writing.<br /><br /><br /><b>10. Questions or Comments</b></p>
<p style="text-align: justify;">If you have any questions, concerns, comments or complaints about this Privacy Policy and/or our collection or use of personal information, or if you wish us to stop processing your personal information for any particular purpose or purposes, then please contact us or send a letter to bike2biker, Clonmeen, Rhode, Co. Offaly, Ireland. VAT Number IE6647473H.</p>
<p style="text-align: justify;"><br /><br /><br /></p>
<p style="text-align: justify;">&nbsp;</p>
<p style="text-align: justify;">&nbsp;</p>
<p style="text-align: justify;">&nbsp;</p>