<p style="text-align: justify;"><b>Advertising Terms &amp; Conditions</b></p>
<p style="text-align: justify;"><b>Click HERE to view all OUR LEGAL POLICIES</b></p>
<p style="text-align: justify;"><b>ATTENTION &ndash; PLEASE NOTE</b></p>
<ol style="text-align: justify;" start="1">
<li>Whether      you are an advertiser or another user of the Website, access to or use of      this website bike2bkier.com (which includes our blog and all pages      consisting of or containing that address, e.g. bikes.donedeal.com, blog.bike2biker,      help.bike2biker and any page that is enabled for use by a mobile device)      (the &ldquo;<b>Website</b>&rdquo; or &ldquo;<b>bike2biker</b>&rdquo;)      and the provision of our advertising services on this Website are subject      to you accepting our Agreement. That Agreement consists of these      Advertising Terms and Conditions, the Copyright Notice, Legal Disclaimer      and General Terms, our Privacy Policy, our Policies LILNK and our Safety      Guide Link appearing on the      Website (the &ldquo;<strong>Agreement</strong>&rdquo;),      all of which you should read carefully before you start to use the Website.</li>
<li>By      accessing and using this Website, you confirm that you have read,      understand and accept that Agreement and that you agree to abide by its      terms and conditions each time you access and use this Website. If you do      not agree to all of this Agreement you should not use this Website.</li>
<li>Bike2biker      (&ldquo;we&rdquo;, &ldquo;us&rdquo; or &rdquo;our&rdquo;) reserves the absolute right at our sole discretion,      without being obliged to give any reason, to reject, amend or remove any      Content posted or submitted by you any time without notice to you. We      reserve the right to monitor and to review all Content submitted to us,      accessed on or published on bike2biker.com at any time.</li>
<li>Where      ads or other Content are rejected and/or removed from the Website by us,      it is our policy NOT to issue refunds. If you have any doubts about the      suitability of a proposed ad, please contact us in advance of placing the ad for      appropriate guidance.</li>
<li>When      creating an advertisement on our Website you agree to provide accurate,      current and complete information and to promptly update the information      that you provide to us when it changes.</li>
<li>We      do not control the content of advertisements posted by users on the      Website, and we do not guarantee the accuracy, integrity or quality of the      content. You understand that by using the Website, you may be exposed to      content that is offensive, indecent or objectionable without liability.</li>
<li>Please      use the &ldquo;Report Ad&rdquo;      mechanism which we have placed on the Website to report any advertisement      that is in breach of this Agreement, illegal or in any other way      objectionable.</li>
<li>You      must be 18 years of age or older to use our Website.</li>
<li>Using      multiple brand names/search words means that ads appear in the wrong      category and search lists, making them inaccurate and therefore we do not      allow the use of these in any form on our site.</li>
</ol>
<div>
<p style="text-align: justify;"><b>Advertiser General Terms &amp; Conditions</b></p>
<p style="text-align: justify;">To use our Website to advertise goods which you have for sale you agree to comply with the following general terms and conditions relating to advertising: Please also refer to our Copyright Notice, Legal Disclaimer and General Terms prior to posting any advertisement.</p>
<p style="text-align: justify;"><b>Illegal or Offending Ads</b></p>
<p style="text-align: justify;">Ads containing illegal, defamatory, obscene, indecent or otherwise offending material are not allowed on our Website.</p>
<p style="text-align: justify;"><b>Goods Only</b></p>
<p style="text-align: justify;">Only goods may be advertised on our Website. Services may not be advertised.<br /><br /></p>
<p style="text-align: justify;"><b>Copyright and intellectual property rights</b></p>
<p style="text-align: justify;">You are solely responsible for any Content that you submit, publish or display on the Website or transmit to other Website users.</p>
<p style="text-align: justify;">You are solely responsible for your advertisements listed on our Website. You understand that all information publicly posted or privately transmitted through the Website is the sole responsibility of the person from which/whom such content originated and that we will not be liable for any errors or omissions in any content or as a result of any user&rsquo;s use of the Website. You understand that we cannot guarantee the identity of any other users with whom you may interact in the course of using the bike2biker Service. Additionally, we cannot guarantee the authenticity of any data which users may provide about themselves or relationships they may describe.</p>
<p style="text-align: justify;">By posting Content on the Website, you grant to us, and you represent and warrant that you have the right to grant, us, our contractors, and the users of the Website an irrevocable, perpetual, royalty-free, fully sub-licensable, fully paid up, worldwide license to use, copy, publicly perform, digitally perform, publicly display, and distribute such Content and to prepare derivative works of, or incorporate into other works, such Content. This licence is non-exclusive, except you agree that we shall have the exclusive right to exercise this license to the extent of combining your Content with the Content of other users for purposes of constructing or populating a searchable database of advertisements. You understand that this licence allows us to reformat, excerpt, or translate any materials submitted by you.</p>
<p style="text-align: justify;">The Copyright Notice, Legal Disclaimer and General Terms contain further obligations, standards and restrictions related to the Content that you submit, publish or display on the Website or transmit to other Website users. Please familiarise yourself with those terms and conditions.<br /><br /></p>
<p style="text-align: justify;"><b>Standards</b></p>
<p style="text-align: justify;">All advertisements must adhere to the &ldquo;Code of Advertising Standards&rdquo; as defined by&nbsp;<a title="Home Page for Advertising Standards Authority for Ireland" target="_blank" href="http://www.donedeal.ie/donedeal/redirect.jsp?redir=http://www.asai.ie/">The Advertising Standards Authority for Ireland</a>&nbsp;in addition to the standards set out in this Agreement.</p>
<p style="text-align: justify;"><b>Review</b></p>
<p style="text-align: justify;">We endeavour to ensure that all ads published on bike2biker are reviewed by our staff either in advance or shortly after they appear on the Website. We reserve the right to reject ads that do not comply with our Agreement, and to delete these ads without notice or refund. You agree that delays may occur in the ads appearing on the Website to facilitate our review of the ads.</p>
<p style="text-align: justify;"><b>Responsibility</b></p>
<p style="text-align: justify;">You are personally responsible for the Content appearing in any of your ads and for the goods sold following advertisement. We are not responsible for the goods appearing on the Website that you advertise or purchase, nor are we responsible for the Content appearing in any of the ads. To the extent permitted by law we disclaim all liability and responsibility arising from any reliance placed on the content of any ad by any user of our Website.</p>
<p style="text-align: justify;"><b>Commercial Advertising</b></p>
<p style="text-align: justify;">Businesses and persons acting in the course of trade are welcome to place classifieds ads on the Website. Ads published by businesses or persons acting in the course of trade must comply with applicable laws and it your responsibility to do so. We will hold you responsible for any failure to comply with laws that apply to you or your content. You may need to adhere to the Consumer Protection Act 2007, the European Communities (Misleading and Comparative Marketing Communications) Regulations 2007, the European Communities (Misleading Advertising) Regulations 1988, European Communities (Protection of Consumers in Respect of Contracts made by means of Distance Communications) Regulations 2001, the European Communities (Directive 2001/31/EC) Regulations, 2003 (the &ldquo;Ecommerce Regulations&rdquo;) and any other consumer protection legislation at the time being in force. Please note that this Website is aimed at consumers in Ireland and Unit Kingdom, but we cannot prevent you being contacted from other consumers or other third parties nor can we prevent your advertisement being displayed in other jurisdictions.</p>
<p style="text-align: justify;"><b>Status of these Terms and Conditions</b></p>
<p style="text-align: justify;">These Terms and Conditions form part of our Agreement with you concerning use of our Website, link to legal&rsquo; all of which you should read carefully before you start to use this Website.&nbsp;By accessing and using this Website, you indicate that you have read, understand and accept that Agreement, and that you agree to abide by its terms and conditions each time you access and use this Website. If you do not agree to all of the terms and conditions of the Agreement you should not use this Website.</p>
<p><br /><br /></p>
</div>
<div></div>
<p>&nbsp;</p>